# Scegli il profilo di default da usare (puoi sovrascrivere da CLI: --profile single|multi)
profile: single

# ------------------- Configurazioni comuni -------------------
common:
  model:
    name: llava
    quantization: fp32
    dropout_p: 0.3
    deeper_head: false
    hidden_dim: 512
    backbone:
      freeze: true            # true = backbone congelata sempre
      unfreeze_last_k: 0      # >0 = sblocca ultimi k layer (valido solo se freeze=true)
      unfreeze_parts: all      # all | attn | mlp
      include_embeddings: true # true = include anche embeddings (valido solo se freeze=true)

  data:
    base_path: null
    batch_size: 256
    num_workers: 8

  train:
    epochs: 100
    lr: 0.0001                # LR teste di classificazione
    backbone_lr: 0.0001       # LR backbone (può essere uguale a lr)
    weight_decay: 0.0001
    patience: 10
    amp: true
    eval_every: 1
    scheduler:
      type: reduce_on_plateau
      factor: 0.1
      threshold: 1.0e-4

# ------------------- Configurazioni profilo single-task -------------------
single:
  task: gender
  model:
    backbone:
      freeze: true            # true = backbone congelata sempre
      unfreeze_last_k: 0      # >0 = sblocca ultimi k layer (valido solo se freeze=true)

#------------------- Configurazioni profilo multi-task -------------------
multi:
  tasks: [age, gender, emotion]
  model:
    backbone:
      freeze: true             # true = backbone congelata
      unfreeze_last_k: 4       # >0 = sblocca ultimi k layer (valido solo se freeze=true)
      unfreeze_parts: all      # all | attn | mlp
      include_embeddings: true # true = include anche embeddings (valido solo se freeze=true)
  train:
    lr: 0.0001                 # LR teste di classificazione
    backbone_lr: 0.00005       # LR backbone (può essere uguale a lr)

    running_means:
      enabled: true
      alpha: 0.95   # più vicino a 1 => più liscio

    # Pesi statici di fallback (usati quando EMA non è ancora inizializzata)
    task_weights:
      age: 1.0
      gender: 1.0
      emotion: 1.0